version: '3.7'
services:
  web:
    image: httpd:latest
    container_name: apache-container
    ports:
      - "8000:80"
    volumes:
      - ./app:/usr/local/apache2/htdocs
  php:
    build:
      dockerfile: php7-apache2-dockerfile
      context: .
    image: php:7.4-apache
    container_name: php-container
    ports:
      - "8082:80"
      - "443:443"
    volumes:
      - /home/robson/projetos/app:/var/www/html
    links:
      - mysqldb
  mysqldb:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3307:3306"
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=devops123
      - MYSQL_DATABASE=desafio
